server:
  port: 8080
spring:
  application:
    name: JOSP-takeAway
  # 可以手动指定，不指定就是上面包名的默认名称
  redis:
    host: localhost
    port: 6379
    database: 0 # 配置了16个数据库，这里使用的是0号数据库
    #password: # 设置默认密码
    jedis:
      # redis连接池配置
      pool:
        max-active: 8 # 最大连接数
        max-wait: 1ms # 阻塞最大等待时间
        max-idle: 4 # 最大空闲连接
        min-idle: 0 # 最小空闲连接
  cache:
    redis:
      time-to-live: 18000 #设置缓存有效期
  # password: 123456
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: LIU18959297292
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
  shardingsphere:
    # 不清楚这里是否用这个名称定义配置
    datasource:
      names:
        # 定义了两个数据源，分别是主库从库
        master,slave
      # 主数据源
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        # driver-class-name: com.mysql.cj.jdbc.Driver
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.138.100:3306/rw?characterEncoding=utf-8
        username: root
        password: root
      # 从数据源,根据上面的数据源分别定义主库和从库的具体配置
      # 这里因为yml无法读取具体的参数，所以一直是标红，先全部注掉
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.138.101:3306/rw?characterEncoding=utf-8
        username: root
        password: root
    masterslave:
      # 上面是负载均衡的配置
      # 读写分离配置
      load-balance-algorithm-type: round_robin # 轮询
      # round_robin，负载均衡的策略
      # 如果我有多个从库，那么查询过来的时候，我轮流执行一遍即可
      # 最终的数据源名称
      name: dataSource
      # 主库数据源名称
      master-data-source-name: master
      # 从库数据源名称列表，多个逗号分隔
      slave-data-source-names: slave
    props:
      sql:
        show: true # 开启SQL显示，默认false
  main:
    # 直接启动的时候，会导致多个DataSource定义的bean出现，进而导致bean定义冲突，启动失败
    allow-bean-definition-overriding: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: assign_id
reggie:
  common-path: C:\Users\junw\Desktop\demoFile\