server:
  port: 8080
spring:
  application:
    name: reggie_takeaway
  # 可以手动指定，不指定就是上面包名的默认名称
  redis:
    host: localhost
    port: 6379
    database: 0 #配置了16个数据库，这里使用的是0号数据库
  cache:
    jedis:
      # redis连接池配置
      pool:
        max-active: 8 #最大连接数
        max-wait: 1ms #阻塞最大等待时间
        max-idle: 4 #最大空闲连接
        min-idle: 0 #最小空闲连接
    redis:
      time-to-live: 18000 #设置缓存有效期
  # password: 123456
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: LIU18959297292
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: assign_id
reggie:
  common-path: C:\Users\junw\Desktop\demoFile\
